export const CHAT_SET_USER_INFO = 'CHAT_SET_USER_INFO';
export const CHAT_ADD_POST_TO_HISTORY = 'CHAT_ADD_POST_TO_HISTORY';

export const CHAT_CLEAR_HISTORY = 'CHAT_CLEAR_HISTORY';

export const CHAT_SET_MESSAGE = 'CHAT_SET_MESSAGE';
export const CHAT_SET_CAN_I_SEND_MESSAGE = 'CHAT_SET_CAN_I_SEND_MESSAGE';
export const CHAT_SET_SEND_MESSAGE_COUNTDOWN = 'CHAT_SET_SEND_MESSAGE_COUNTDOWN';

export const USER_SET_IS_LOGGED_IN = 'USER_SET_IS_LOGGED_IN';
export const USER_SET_USERNAME = 'USER_SET_USERNAME';
export const USER_SET_PASSWORD = 'USER_SET_PASSWORD';
export const USER_SET_TOKEN = 'USER_SET_TOKEN';
export const USER_SET_IS_MUTED = 'USER_SET_IS_MUTED';
export const USER_SET_IS_BANNED = 'USER_SET_IS_BANNED';

export const USERSLIST_SET_ONLINE_LIST = 'USERSLIST_SET_ONLINE_LIST';
export const USERSLIST_SET_BANNED_LIST = 'USERSLIST_SET_BANNED_LIST';

export const USERSLIST_CLEAR_LIST = 'USERSLIST_CLEAR_LIST';
