export const CHAT_GET_DATA_FROM_SERVER = 'CHAT_GET_DATA_FROM_SERVER';
export const CHAT_ADD_POST_TO_HISTORY = 'CHAT_ADD_POST_TO_HISTORY';

export const CHAT_CLEAR_HISTORY = 'CHAT_CLEAR_HISTORY';

export const CHAT_SET_MESSAGE = 'CHAT_SET_MESSAGE';
export const CHAT_SET_CAN_I_SEND_MESSAGE = 'CHAT_SET_CAN_I_SEND_MESSAGE';
export const CHAT_SET_SEND_MESSAGE_COUNTDOWN = 'CHAT_SET_SEND_MESSAGE_COUNTDOWN';

// export const CHAT_MESSAGE_SENT = 'CHAT_MESSAGE_SENT';
// export const CHAT_MESSAGE_RECEIVED = 'CHAT_MESSAGE_RECEIVED';
//
// export const CHAT_USER_CONNECTED = 'CHAT_USER_CONNECTED';
// export const CHAT_USER_DISCONNECTED = 'CHAT_USER_DISCONNECTED';

export const USER_SET_IS_LOGGED_IN = 'USER_SET_IS_LOGGED_IN';
export const USER_SET_USERNAME = 'USER_SET_USERNAME';
export const USER_SET_PASSWORD = 'USER_SET_PASSWORD';

